### ISSUE TITLE
Documentation Problems

### ISSUE THREAD

**Issue by MadocGwyn** [RimWorld-CCL-Reborn/AlienRaces#17]
Just started working with this. Was following the documentation and ran into some problems with the documentation. 
1) The graphics path, one is updated to the north/south format the other still says front/back.
2) I tried to get a minimal config to load in game and ran into a problem. It was getting a null reference exception trying to generate the meat defs. Adding a snippet that I stole from ElderThings fixed it. I'm not sure if they are both required: 
```xml
<race>
      <meatLabel>secretrace meat</meatLabel>
      <meatMarketValue>0.8</meatMarketValue>
</race>
```
Should it not have a default? 

ONE of the three mods in the list in the steam listing is actually updated to the new version (Elder things) so it's a good example.

**Comment by erdelf** [comment]
the race tag is the one that is important for the meat generator. The others.. not so much.

The race tag is not part of the framework, but of vanilla and is therefore not following the more user friendly rules of the framework you assumed. I suggest copying the human race tag, since that is what you probably want.
